version: '3'
services:
  shortie:
    image: jk779/shortie:latest
    command: bundle exec puma -C config/puma.rb
    volumes:
      - /home/michael/docker/shortie/production.sqlite3:/app/db/production.sqlite3
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    # ports:
    #   - "3000:3000"

  cloudflared-tunnel:
    container_name: cf-tunnel-shortie
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
